theme: jekyll-theme-minimal

title: [ML-Journal]
description: [Machine Learning in Architecture]

logo: [https://github.com/gizemef/ML-Journal/blob/master/5dd2cac879d757330b3ab572.jpg]
google_analytics: [Your Google Analytics tracking ID]
